### ISSUE TITLE
Datenbank Tabellen löschen

### ISSUE THREAD

**Issue by Benjamin-Scherf** [heimrichhannot/contao-frontendedit#2]
Ich habe zum Test die Extension installiert, dann wieder versucht zu deinstallieren.

Sämtliche folgende Tabellen können nicht gelöscht werden.

ALTER TABLE tl_module DROP useModal
--
  | ALTER TABLE tl_module DROP visibleStatusMessages
  | ALTER TABLE tl_module DROP block
  | ALTER TABLE tl_module DROP hideAutoItem
  | ALTER TABLE tl_module DROP formHybridDataContainer
  | ALTER TABLE tl_module DROP formHybridViewMode
  | ALTER TABLE tl_module DROP formHybridForcePaletteRelation
  | ALTER TABLE tl_module DROP formHybridEditable
  | ALTER TABLE tl_module DROP formHybridAddEditableRequired
  | ALTER TABLE tl_module DROP formHybridEditableRequired
  | ALTER TABLE tl_module DROP formHybridAddReadOnly
  | ALTER TABLE tl_module DROP formHybridReadOnly
  | ALTER TABLE tl_module DROP formHybridAddDisplayedSubPaletteFields
  | ALTER TABLE tl_module DROP formHybridDisplayedSubPaletteFields
  | ALTER TABLE tl_module DROP formHybridEditableSkip
  | ALTER TABLE tl_module DROP formHybridAddDefaultValues
  | ALTER TABLE tl_module DROP formHybridDefaultValues
  | ALTER TABLE tl_module DROP formHybridTemplate
  | ALTER TABLE tl_module DROP formHybridReadonlyTemplate
  | ALTER TABLE tl_module DROP formHybridCustomSubTemplates
  | ALTER TABLE tl_module DROP formHybridAction
  | ALTER TABLE tl_module DROP formHybridAddHashToAction
  | ALTER TABLE tl_module DROP formHybridCustomHash
  | ALTER TABLE tl_module DROP removeAutoItemFromAction
  | ALTER TABLE tl_module DROP formHybridCssClass
  | ALTER TABLE tl_module DROP formHybridStartTemplate
  | ALTER TABLE tl_module DROP formHybridStopTemplate
  | ALTER TABLE tl_module DROP formHybridAsync
  | ALTER TABLE tl_module DROP formHybridSuccessMessage
  | ALTER TABLE tl_module DROP formHybridSkipScrollingToSuccessMessage
  | ALTER TABLE tl_module DROP formHybridSendSubmissionAsNotification
  | ALTER TABLE tl_module DROP formHybridSubmissionNotification
  | ALTER TABLE tl_module DROP formHybridSendConfirmationAsNotification
  | ALTER TABLE tl_module DROP formHybridConfirmationNotification
  | ALTER TABLE tl_module DROP formHybridAddFieldDependentRedirect
  | ALTER TABLE tl_module DROP formHybridFieldDependentRedirectKeepParams
  | ALTER TABLE tl_module DROP formHybridCustomSubmit
  | ALTER TABLE tl_module DROP formHybridSubmitLabel
  | ALTER TABLE tl_module DROP formHybridSubmitClass
  | ALTER TABLE tl_module DROP formHybridAddPermanentFields
  | ALTER TABLE tl_module DROP formHybridPermanentFields
  | ALTER TABLE tl_module DROP formHybridSingleSubmission
  | ALTER TABLE tl_module DROP formHybridResetAfterSubmission
  | ALTER TABLE tl_module DROP formHybridJumpToPreserveParams
  | ALTER TABLE tl_module DROP formHybridUseCustomFormId
  | ALTER TABLE tl_module DROP formHybridCustomFormId
  | ALTER TABLE tl_module DROP formHybridUseCustomFormIdSuffix
  | ALTER TABLE tl_module DROP formHybridCustomFormIdSuffix
  | ALTER TABLE tl_module DROP formHybridAllowIdAsGetParameter
  | ALTER TABLE tl_module DROP formHybridIdGetParameter
  | ALTER TABLE tl_module DROP formHybridAppendIdToUrlOnCreation
  | ALTER TABLE tl_module DROP formHybridTransformGetParamsToHiddenFields
  | ALTER TABLE tl_module DROP formHybridCreatePdfAfterSubmission
  | ALTER TABLE tl_module DROP formHybridEnableAutoComplete
  | ALTER TABLE tl_module DROP formHybridAddExportButton
  | ALTER TABLE tl_module DROP formHybridAddOptIn
  | ALTER TABLE tl_module DROP formHybridOptInNotification
  | ALTER TABLE tl_module DROP formHybridOptInSuccessMessage
  | ALTER TABLE tl_module DROP formHybridOptInConfirmedProperty
  | ALTER TABLE tl_module DROP formHybridOptInModelRetrievalProperty
  | ALTER TABLE tl_module DROP formHybridOptInJumpTo
  | ALTER TABLE tl_module DROP formHybridAddOptOut
  | ALTER TABLE tl_module DROP formHybridOptOutSuccessMessage
  | ALTER TABLE tl_module DROP formHybridOptOutJumpTo
  | ALTER TABLE tl_module DROP formHybridfilterTokenFields
  | ALTER TABLE tl_module DROP formHybridTokenFields
  | ALTER TABLE tl_module DROP formHybridAddGetParameter
  | ALTER TABLE tl_module DROP formHybridGetParameter
  | ALTER TABLE tl_module DROP formHybridFieldDependentRedirectConditions
  | ALTER TABLE tl_module DROP formHybridFieldDependentRedirectJumpTo
  | ALTER TABLE tl_module DROP addDetailsCol
  | ALTER TABLE tl_module DROP jumpToDetails
  | ALTER TABLE tl_module DROP addShareCol
  | ALTER TABLE tl_module DROP jumpToShare
  | ALTER TABLE tl_module DROP shareAutoItem
  | ALTER TABLE tl_module DROP sortingMode
  | ALTER TABLE tl_module DROP filterMode
  | ALTER TABLE tl_module DROP itemSorting
  | ALTER TABLE tl_module DROP hideFilter
  | ALTER TABLE tl_module DROP showItemCount
  | ALTER TABLE tl_module DROP showInitialResults
  | ALTER TABLE tl_module DROP addAjaxPagination
  | ALTER TABLE tl_module DROP addInfiniteScroll
  | ALTER TABLE tl_module DROP addMasonry
  | ALTER TABLE tl_module DROP masonryStampContentElements
  | ALTER TABLE tl_module DROP addProximitySearch
  | ALTER TABLE tl_module DROP proximitySearchAllowGeoLocation
  | ALTER TABLE tl_module DROP proximitySearchCoordinatesMode
  | ALTER TABLE tl_module DROP proximitySearchCoordinatesField
  | ALTER TABLE tl_module DROP proximitySearchLatField
  | ALTER TABLE tl_module DROP proximitySearchLongField
  | ALTER TABLE tl_module DROP proximitySearchCityField
  | ALTER TABLE tl_module DROP proximitySearchPostalField
  | ALTER TABLE tl_module DROP proximitySearchStateField
  | ALTER TABLE tl_module DROP proximitySearchCountryField
  | ALTER TABLE tl_module DROP proximitySearchCountryFallback
  | ALTER TABLE tl_module DROP isTableList
  | ALTER TABLE tl_module DROP hasHeader
  | ALTER TABLE tl_module DROP sortingHeader
  | ALTER TABLE tl_module DROP tableFields
  | ALTER TABLE tl_module DROP customFilterFields
  | ALTER TABLE tl_module DROP filterArchives
  | ALTER TABLE tl_module DROP filterGroups
  | ALTER TABLE tl_module DROP setPageTitle
  | ALTER TABLE tl_module DROP pageTitleField
  | ALTER TABLE tl_module DROP pageTitlePattern
  | ALTER TABLE tl_module DROP additionalWhereSql
  | ALTER TABLE tl_module DROP additionalSelectSql
  | ALTER TABLE tl_module DROP additionalSql
  | ALTER TABLE tl_module DROP additionalHavingSql
  | ALTER TABLE tl_module DROP hideUnpublishedItems
  | ALTER TABLE tl_module DROP publishedField
  | ALTER TABLE tl_module DROP invertPublishedField
  | ALTER TABLE tl_module DROP emptyText
  | ALTER TABLE tl_module DROP filterHeadline
  | ALTER TABLE tl_module DROP itemTemplate
  | ALTER TABLE tl_module DROP useDummyImage
  | ALTER TABLE tl_module DROP dummyImage
  | ALTER TABLE tl_module DROP disableSessionCheck
  | ALTER TABLE tl_module DROP disableAuthorCheck
  | ALTER TABLE tl_module DROP conjunctiveMultipleFields
  | ALTER TABLE tl_module DROP addDisjunctiveFieldGroups
  | ALTER TABLE tl_module DROP disjunctiveFieldGroups
  | ALTER TABLE tl_module DROP addExistanceConditions
  | ALTER TABLE tl_module DROP aliasField
  | ALTER TABLE tl_module DROP existanceConditions
  | ALTER TABLE tl_module DROP appendIdToUrlOnFound
  | ALTER TABLE tl_module DROP addShowConditions
  | ALTER TABLE tl_module DROP showConditions
  | ALTER TABLE tl_module DROP deactivateTokens
  | ALTER TABLE tl_module DROP formHybridLinkedList
  | ALTER TABLE tl_module DROP formHybridLinkedFilter
  | ALTER TABLE tl_module DROP useSelectSorting
  | ALTER TABLE tl_module DROP addEntityIdFilter
  | ALTER TABLE tl_module DROP entityFilterIds
  | ALTER TABLE tl_module DROP addFreetextSearch
  | ALTER TABLE tl_module DROP freetextSearchFields
  | ALTER TABLE tl_module DROP saveFilterToSession
  | ALTER TABLE tl_module DROP enableFuzzySearch
  | ALTER TABLE tl_module DROP limitFormattedFields
  | ALTER TABLE tl_module DROP formattedFields
  | ALTER TABLE tl_module DROP addEditCol
  | ALTER TABLE tl_module DROP jumpToEdit
  | ALTER TABLE tl_module DROP useModalForEdit
  | ALTER TABLE tl_module DROP addDeleteCol
  | ALTER TABLE tl_module DROP addPublishCol
  | ALTER TABLE tl_module DROP useModalForCreate
  | ALTER TABLE tl_module DROP addCreateButton
  | ALTER TABLE tl_module DROP createButtonLabel
  | ALTER TABLE tl_module DROP createMemberGroups
  | ALTER TABLE tl_module DROP jumpToCreate
  | ALTER TABLE tl_module DROP defaultArchive
  | ALTER TABLE tl_module DROP deleteNotification
  | ALTER TABLE tl_module DROP noIdBehavior
  | ALTER TABLE tl_module DROP addUpdateConditions
  | ALTER TABLE tl_module DROP updateConditions
  | ALTER TABLE tl_module DROP allowDelete
  | ALTER TABLE tl_module DROP jumpToAfterDelete
  | ALTER TABLE tl_module DROP addDeleteConditions
  | ALTER TABLE tl_module DROP deleteConditions
  | ALTER TABLE tl_module DROP addClientsideValidation
  | ALTER TABLE tl_module DROP publishOnValid
  | ALTER TABLE tl_module DROP changePasswordJumpTo

Was muss ich tun um diese wieder aus der Datenbakn zu bekommen?

**Comment by Defcon0** [comment]
Die Felder werden ganz normal über die DCA-Dateien angelegt. Daher müssen sie auch ganz normal über das Datenbank-Tool entfernbar sein. Wie äußert es sich denn, dass es bei dir nicht geht? Kommt eine Fehlermeldung? Welche Contao-Version nutzt du?

**Comment by Benjamin-Scherf** [comment]
Die Version ist 4.8.4

Das Log sieht wie folgt aus:

[2019-12-04 19:10:03] request.INFO: Matched route "contao_install". {"route":"contao_install","route_parameters":{"_route":"contao_install","_scope":"backend","_token_check":true,"_controller":"Contao\\InstallationBundle\\Controller\\InstallationController::installAction"},"request_uri":"https://ebstorf.tasc-app.de/contao/install","method":"POST"} []

[2019-12-04 19:10:04] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'ALTER TABLE tl_module DROP useModal':  SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs" at /home/www/ebstorf.tasc-app.de/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 106 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'ALTER TABLE tl_module DROP useModal':\n\nSQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs at /home/www/ebstorf.tasc-app.de/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:106, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs at /home/www/ebstorf.tasc-app.de/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:80, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs at /home/www/ebstorf.tasc-app.de/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:75)"} []

**Comment by Defcon0** [comment]
> 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126.

Die Spalten deiner Tabelle sind insgesamt gerechnet zu groß. Interessant ist, das selbst das löschen nicht klappt. Hast du mal versucht, bspw. useModal von Hand zu löschen in phpmyadmin? Oder du erhöhst die maximale Größe. Jedenfalls hat das nichts mit dem Modul zu tun.
